name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of JD.SemanticKernel.Connectors.ClaudeCode are you using?
      placeholder: "1.0.0-preview.42"
    validations:
      required: true

  - type: dropdown
    id: tfm
    attributes:
      label: Target Framework
      options:
        - net8.0
        - net10.0
        - netstandard2.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue.
      render: csharp
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include stack traces if applicable.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: OS, IDE, Claude Code version, or other relevant details.
    validations:
      required: false
